env:
  RUBY_VERSION: 2.6.x
  RAILS_ENV: test  
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: tn_qna_test
  RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}

name: Rails tests

on: [push,pull_request]

jobs:
  rspec-test:

    name: RSpec
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: tn_qna_test
          POSTGRES_HOST: localhost
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_PORT: ${{ job.services.postgres.ports[5432] }}
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

      redis:
        image: redis
        ports:
          - 6379:6379
        options: --entrypoint redis-server
        env:
          REDIS_HOST: localhost
          REDIS_PORT: 6379

      elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3
        env:
          ES_CLUSTER_NAME: project-test-cluster
          ES_NETWORK_HOST: 127.0.0.1
        ports:
          - 9200:9350

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
      - name: Install postgres client
        run: sudo apt-get install libpq-dev

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 10.13.0

      - name: Install packages
        run: |
          yarn install --pure-lockfile

      - name: Install dependencies
        run: |
          gem install bundler
          bundler install
      - name: Create database
        run: |
          cp config/database.yml.github-actions config/database.yml
          bundler exec rails db:create RAILS_ENV=test
          bundler exec rails db:migrate RAILS_ENV=test
        env:
          RAILS_ENV: test
          POSTGRES_DB: tn_qna_test
          POSTGRES_HOST: localhost
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_PORT: ${{ job.services.postgres.ports[5432] }}

      - name: Run tests
        run: bundler exec rake
        env:
          RAILS_ENV: test
          POSTGRES_DB: tn_qna_test
          POSTGRES_HOST: localhost
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_PORT: ${{ job.services.postgres.ports[5432] }}
          REDIS_HOST: localhost
          REDIS_PORT: 6379
